233 scrape examples 2
dimforge/parry pull request #242
Opened 2024-07-23 14:19 UTC by Vrixyz

Builds on top of https://github.com/dimforge/parry/pull/241

2024-07-23 19:21 UTC, waywardmonkeys requested changes

2024-07-23 19:21 UTC, waywardmonkeys commented on crates/parry2d/Cargo.toml
> +cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
You don’t need to pass a cfg, docs.rs does that already.

I don’t think you can use all-features due to dim2/dim3 and f32/f64

you can do this like I do elsewhere:

```

[package.metadata.docs.rs]
rustdoc-args = [ "-Zunstable-options", "--generate-link-to-definition"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
```

2024-07-23 19:21 UTC, waywardmonkeys commented on crates/parry3d/Cargo.toml
> +[package.metadata.docs.rs]
As above…

2024-07-26 14:22 UTC, Vrixyz commented on crates/parry2d/Cargo.toml
> +doc-scrape-examples = true
Add a comment to explain why all examples are listed (rustdoc scrape examples)

+ check if rustc has planned to facilitate this configuration

2024-08-02 09:57 UTC, sebcrozet approved these changes
🎉

2024-08-02 10:00 UTC, waywardmonkeys approved these changes

2024-08-02 10:06 UTC, merged